### ISSUE TITLE
[Teampura#1] Comments vanish after one or few refreshes on the station s/SampleStation

### ISSUE THREAD

**Issue by carlosshi1** [silentrald/STSWENG_Reddit#19]
&nbsp; | &nbsp;
-|-
ID | Teampura#1
Title | Comments that are posted vanish after one or few refreshes on the station s/SampleStation
Reporter | Carlos Shi
Date | Jan 15, 2021
Environment | Firefox 84.0.2 (64-bit), Windows 10 Home 18363.1316

**Description:** 
After signing up and logging in, I went to check one of the sample "subreddits" and I created a post. After that I commented on it, and it vanished when I refreshed it.

**Steps to reproduce:**
1. Log in to an account
2. Click on the SampleStation on the right
3. Click on a post like this one
![image](https://user-images.githubusercontent.com/56996127/104623823-b763fd80-56cd-11eb-898b-dffb499de674.png)
4. Write a comment
5. Post the comment
6. Refresh the browser or navigate away then come back

**Expected Result:** 
Comments should stay on screen after navigating away then coming back.
**Actual Result:**
Comments disappear after one or a few refreshes.

**Attachments:**
![ezgif-4-b170b5364898](https://user-images.githubusercontent.com/56996127/104624454-8cc67480-56ce-11eb-9931-154153c811b4.gif)

**Comment by theaellengo** [comment]
Is the user commenting a member of the station?

**Comment by carlosshi1** [comment]
Hello, I wasn't joined in the report above so I joined the station called s/SampleStation and recorded it once more. Sometimes it takes multiple refreshes to happen or moving away from that page.
![image](https://user-images.githubusercontent.com/56996127/104728623-209d4c80-5772-11eb-872b-63de008be582.png)

**Comment by theaellengo** [comment]
Will be considered a bug, thank you!

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#10] Comments Vanishing After Refresh](https://trello.com/c/3qff0wP2/66-us10-comments-vanishing-after-refresh)
