### ISSUE TITLE
[GImmIckk] No definition of a strong password

### ISSUE THREAD

**Issue by chrissyv09** [silentrald/STSWENG_Reddit#20]
## Defect R.1
Date: Thursday 14 Jan 2021
| | |
|-|-|
Title | [SignUp] No definition of a strong password  
Description | Input a string password
Reporter | Team GImmICK (Vinco)
Device/OS used | macOS - Google Chrome
Prerequisite | The user is on the [Sign Up page](https://stsweng-reddit-stage.vercel.app/sign-up).
Priority level | Low

<br>

Steps to Reproduce:
1. Input a valid Username
2. Input a valid Email address 
3. Input a string “testing” for the Password text input 
4. Input the same string for the Confirm Password text input 
5. Click Sign Up 
6. An error shows that password was too weak
7. Changed input to testing123 
8. Click Sign Up 
9. An error shows that password was too weak

<br>

Expected Result: 
Notifies user that the password is too weak with a description of an expected strong password 

<br>

Actual Result: 
Notifies the user that the password is too weak  <be> 
<img width="279" alt="Screen Shot 2021-01-14 at 9 50 12 PM" src="https://user-images.githubusercontent.com/60336554/104686648-7ca09c00-56b2-11eb-9c41-5f08fddd50e7.png">

<br>

**Comment by theaellengo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Max Length Text Boxes (Front-End)](https://trello.com/c/62h5nU7K/53-us1-registration-max-length-text-boxes-front-end)
