### ISSUE TITLE
[GImmICK] Title exceeds the container

### ISSUE THREAD

**Issue by chrissyv09** [silentrald/STSWENG_Reddit#23]
## Defect R.4
Date: Thursday 14 Jan 2021
| | |
|-|-|
Title | [Post to a Station] Title exceeds the container
Description | Title exceeds container when a long input is placed when a post is created with 64 characters
Reporter | Team GImmICK (Vinco)
Device/OS used | macOS - Google Chrome
Prerequisite | The user is on the [Add Post page](https://stsweng-reddit-stage.vercel.app/s/ABCD/add-post).
Priority level | Low

<br>

Steps to Reproduce:
1. Input a string with 64 characters for the Title of the post  
2. Input a valid string for the body 

<br>

Expected Result: 
The post is posted with the Title fitting within the post container 

<br>

Actual Result: 
The Title exceeds the post container   <be> 
<img width="446" alt="Screen Shot 2021-01-14 at 9 58 44 PM" src="https://user-images.githubusercontent.com/60336554/104687233-adcd9c00-56b3-11eb-8dba-1658c4d4fc6b.png">

<br>

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#7] Post Create Max Length Text Boxes (Front-End)](https://trello.com/c/n97V1jx8/52-us7-post-create-max-length-text-boxes-front-end)
