### ISSUE TITLE
[GImmICK] Body exceeds the container 

### ISSUE THREAD

**Issue by chrissyv09** [silentrald/STSWENG_Reddit#24]
## Defect R.5
Date: Thursday 14 Jan 2021
| | |
|-|-|
Title | [Post to a Station] Body exceeds the container 
Description | Body exceeds container when a long input is placed when a post is created with 1000 characters 
Reporter | Team GImmICK (Vinco)
Device/OS used | macOS - Google Chrome
Prerequisite | The user is on the [Add Post page](https://stsweng-reddit-stage.vercel.app/s/ABCD/add-post).
Priority level | Low

<br>

Steps to Reproduce:
1. Input a valid post title 
2. Input a string with 1000 characters for the body of the post 

<br>

Expected Result: 
The post is posted with the body fitting within the post container 

<br>

Actual Result: 
The body exceeds the post container   <be> 
<img width="419" alt="Screen Shot 2021-01-14 at 10 01 03 PM" src="https://user-images.githubusercontent.com/60336554/104687418-ff762680-56b3-11eb-9cf2-75be5f445b5a.png">

<br>

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#7] Post Create Max Length Text Boxes (Front-End)](https://trello.com/c/n97V1jx8/52-us7-post-create-max-length-text-boxes-front-end)
