### ISSUE TITLE
[US#10A] Blank Input on the Comment text input

### ISSUE THREAD

**Issue by chrissyv09** [silentrald/STSWENG_Reddit#26]
## Defect R.7
Date: Thursday 14 Jan 2021
| | |
|-|-|
Title | [Add a Comment to a Post] Blank Input
Description | The user is not notified with the error when there is a blank input
Reporter | Team GImmICK (Vinco)
Device/OS used | macOS - Google Chrome
Prerequisite | The user is on the [Comment Test post page](https://stsweng-reddit-stage.vercel.app/s/ABCD/post/puab60EtvSjb) in the ABCD station.
Priority level | Low

<br>

Steps to Reproduce:
1. Click on the comments text box without placing any input 
2. Click on the Post button

<br>

Expected Result: 
An error message is displayed notifying the user of the error  

<br>

Actual Result: 
A red line appears on top of the webpage without any error message   <be> 
<img width="451" alt="Screen Shot 2021-01-14 at 10 07 54 PM" src="https://user-images.githubusercontent.com/60336554/104687926-f5a0f300-56b4-11eb-8f61-3a8877352390.png">

<br>

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#10] Comment Blank Input No Error Message](https://trello.com/c/Y3CL4BSx/59-us10-comment-blank-input-no-error-message)

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#11] Sub-comment Blank Input No Error Message (Front-End)](https://trello.com/c/6T8O9BWk/60-us11-sub-comment-blank-input-no-error-message-front-end)

**Comment by LouisD69** [comment]
Re-opened:

When typing spaces in the comment box, 'Post' button becomes clickable.
Clicking the 'post' button will not post the comment, but also does not show error message
