### ISSUE TITLE
[Teampura#3] Able to comment on a post of a station where I have not joined

### ISSUE THREAD

**Issue by Phantominum** [silentrald/STSWENG_Reddit#31]
| | |
-|-
ID |  Teampura#3
Title |  Able to comment on a post of a station where I have not joined
Reporter | Robin Reyes
Date |  Jan 16, 2021
Environment |  Chrome Version 87.0.4280.141 (Official Build) (64-bit), Windows 10 Home 18363.1316

Description: 
After logging in and selecting a station I am not a part of, I click on a post and I am able to comment despite not having joined the station.

Steps to reproduce:
1. Log into account
2. Click on a station you are not a part of (like the one below)
![image](https://user-images.githubusercontent.com/20613699/104805720-209e5a80-580d-11eb-85cd-a8f11d2bf844.png)
3. Click on a post
4. Comment on the post

Expected Result: 
I should not be able to comment since I am not a member of the station.
Actual Result:
I am able to comment.

Attachments:
![image](https://user-images.githubusercontent.com/20613699/104805780-6eb35e00-580d-11eb-896c-7b4c5375049c.png)

**Comment by theaellengo** [comment]
Hello! Refreshing the page should remove that. The team will work on prompting an error message instead!

**Comment by S0rbetes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#10] Comment works even if user is not joined to a station but only on the front-end](https://trello.com/c/4QgnNq3y/62-us10-comment-works-even-if-user-is-not-joined-to-a-station-but-only-on-the-front-end)
