### ISSUE TITLE
[Sharoan Cunetha #2] Clicking the Post button multiple times when adding a comment adds multiple instances of the comment

### ISSUE THREAD

**Issue by christinedeticio** [silentrald/STSWENG_Reddit#33]
**Description:** When adding a comment on a post, and the Post button is clicked multiple times, multiple instances of the comment are posted.

**Steps to reproduce:**
1. Open the application: https://stsweng-reddit-stage.vercel.app/
2. Log in using valid login credentials.
3. Go to any station’s page.
4. Join the station (if not joined already).
5. Click on one of the posts.
6. Type “Test” on the comment text field.
7. Click “Post” multiple times really quickly.

**Actual results:** Multiple instances of the comment appears.
**Expected results:** Only one instance of the comment is posted.
**Visual proof:**
![Screen Shot 2021-01-16 at 3 20 55 PM](https://user-images.githubusercontent.com/61369402/104806062-9c010b80-580f-11eb-87ed-596e08b17c41.png)

**Defect Report Date:** January 16, 2021

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#10] Clicking the Post button multiple times when adding a COMMENT adds multiple instances of the comment](https://trello.com/c/78AUrwk8/64-us10-clicking-the-post-button-multiple-times-when-adding-a-comment-adds-multiple-instances-of-the-comment)
