### ISSUE TITLE
[Sharoan Cunetha #3] Clicking the Submit button multiple times when creating a post adds multiple instances of the post.

### ISSUE THREAD

**Issue by christinedeticio** [silentrald/STSWENG_Reddit#34]
**Description:** When creating a post, and the Submit button is clicked multiple times, multiple instances of the post are posted.

**Steps to reproduce:**
1. Open the application: https://stsweng-reddit-stage.vercel.app/
2. Log in using valid login credentials.
3. Go to any station’s page.
4. Join the station (if not joined already).
5. Click “Add Post”.
6. Type in valid inputs for the Post Title and Post Body.
7. Click Submit multiple times really quickly.

**Actual results:** Multiple instances of the post appears.
**Expected results:** Only one instance of the post is posted.

**Visual proof:**
![Screen Shot 2021-01-16 at 3 31 49 PM](https://user-images.githubusercontent.com/61369402/104806220-f189e800-5810-11eb-9530-630f851aec8e.png)
![Screen Shot 2021-01-16 at 3 32 14 PM](https://user-images.githubusercontent.com/61369402/104806225-f3ec4200-5810-11eb-86db-57d7aa59acf9.png)

**Defect Report Date:** January 16, 2021

**Comment by theaellengo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issue: No See More for Subcomments](https://trello.com/c/Nr1HNrVe/47-github-issue-no-see-more-for-subcomments)

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#7] Clicking the Submit button multiple times when creating a POST adds multiple instances of the post.](https://trello.com/c/5yWpgIg2/65-us7-clicking-the-submit-button-multiple-times-when-creating-a-post-adds-multiple-instances-of-the-post)

**Comment by theaellengo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Max Length Text Boxes (Front-End)](https://trello.com/c/62h5nU7K/53-us1-registration-max-length-text-boxes-front-end)
