### ISSUE TITLE
[US#29A] [sweng with me] [BUG] Description and Rules paragraph box exceeds the container

### ISSUE THREAD

**Issue by counterPH** [silentrald/STSWENG_Reddit#36]
Inputting/Updating really long description and rules (At least 30 characters long without space) of the station exceeds the container bound of their respective container box.

Bug Report: https://docs.google.com/document/d/1FxRb2Uhqonof6xH7o_uIMXKLsddMwg4f_z6NRTcUw9s/edit?usp=sharing

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#17] Edit Station Max Length Text Boxes (Front-End)](https://trello.com/c/MFLtF4aa/50-us17-edit-station-max-length-text-boxes-front-end)

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#6] Station Create Max Length Text Boxes (Front-End)](https://trello.com/c/RBpjV6qV/51-us6-station-create-max-length-text-boxes-front-end)

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#29A] [sweng with me] [BUG] Description and Rules paragraph box exceeds the container](https://trello.com/c/AFOZLu4Q/92-us29a-sweng-with-me-bug-description-and-rules-paragraph-box-exceeds-the-container)

**Comment by silentrald** [comment]
word-break: break-all;
add this to the container
