### ISSUE TITLE
[Sharoan Cunetha #4] Incorrect error message for existing email upon registration

### ISSUE THREAD

**Issue by sharmainegaw** [silentrald/STSWENG_Reddit#40]
**Description:** When one tries to register using an existing email, an incorrect error message "**Username** is already used" appears. It should be "**Email**".
**Steps to reproduce:**
1. Go to the [sign up page](https://stsweng-reddit-stage.vercel.app/sign-up).
2. Enter an email that's already being used in the 2nd field (for this test case, I used "hello@world", which I had already previously used to register a new account).
3. Enter valid inputs for the rest of the fields.
4. Click sign up.

**Actual results:** An error message "Username is already used" appears.
**Expected results:** An error message "Email is already used" appears.
**Visual proof:**
![image](https://user-images.githubusercontent.com/48157356/104835532-5103f880-58e2-11eb-8a03-3ad0db398573.png)

Defect Report Date: January 17, 2021

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Email Not Repeatable](https://trello.com/c/8YDvX95E/55-us1-registration-email-not-repeatable)

**Comment by theaellengo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Max Length Text Boxes (Front-End)](https://trello.com/c/62h5nU7K/53-us1-registration-max-length-text-boxes-front-end)
