### ISSUE TITLE
[Sharoan Cunetha #5] Invalid email address format (text@text) is accepted

### ISSUE THREAD

**Issue by sharmainegaw** [silentrald/STSWENG_Reddit#41]
**Description:** Invalid email address format is accepted (text@text).
**Steps to reproduce:**
1. Go to the [sign up page](https://stsweng-reddit-stage.vercel.app/sign-up).
2. Enter any unused email in the format text@text.
3. Enter valid inputs for the rest of the fields.
4. Click sign up.

**Actual results:** The invalid email is accepted and a new account is created.
**Expected results:** An error message "Invalid email address" appears and the account isn't created..
**Visual proof:**
_See video below._

**Defect Report Date:** January 17, 2021

https://user-images.githubusercontent.com/48157356/104835807-0be0c600-58e4-11eb-9736-4347cddc97ec.mp4

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Email Accepts string@string](https://trello.com/c/nsENJyOj/67-us1-registration-email-accepts-stringstring)

**Comment by theaellengo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#1] Registration Max Length Text Boxes (Front-End)](https://trello.com/c/62h5nU7K/53-us1-registration-max-length-text-boxes-front-end)
