### ISSUE TITLE
[US#26C] Verification email link undefined

### ISSUE THREAD

**Issue by LouisD69** [silentrald/STSWENG_Reddit#84]
![image](https://user-images.githubusercontent.com/61369999/107110967-1fe66a80-6887-11eb-9181-f6255d4dd223.png)

change undefined to link of deployed website

**Comment by LouisD69** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[US#26C] Verification email link undefined](https://trello.com/c/tdzzTCpl/91-us26c-verification-email-link-undefined)

**Comment by silentrald** [comment]
server/.env
should have this
CLIENT_URL=http://localhost:3000
